// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBi5_JuWfqhwJIbh6c-gNXfsbg77kD89w',
    appId: '1:903844481076:web:bbb801757a36e85150e261',
    messagingSenderId: '903844481076',
    projectId: 'trivo-e78fe',
    authDomain: 'trivo-e78fe.firebaseapp.com',
    storageBucket: 'trivo-e78fe.firebasestorage.app',
    measurementId: 'G-5C6HK1LVZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKo5T7ijK5XKfeKMFNnq5_1XW3GoTfOSM',
    appId: '1:903844481076:android:82c51f25f9c995d650e261',
    messagingSenderId: '903844481076',
    projectId: 'trivo-e78fe',
    storageBucket: 'trivo-e78fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC85fKCktZEGf-cOYI7HdRdQHwoho6vr8c',
    appId: '1:903844481076:ios:b6322a0ac63667e050e261',
    messagingSenderId: '903844481076',
    projectId: 'trivo-e78fe',
    storageBucket: 'trivo-e78fe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC85fKCktZEGf-cOYI7HdRdQHwoho6vr8c',
    appId: '1:903844481076:ios:b6322a0ac63667e050e261',
    messagingSenderId: '903844481076',
    projectId: 'trivo-e78fe',
    storageBucket: 'trivo-e78fe.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBi5_JuWfqhwJIbh6c-gNXfsbg77kD89w',
    appId: '1:903844481076:web:906cc3fb443fcbd550e261',
    messagingSenderId: '903844481076',
    projectId: 'trivo-e78fe',
    authDomain: 'trivo-e78fe.firebaseapp.com',
    storageBucket: 'trivo-e78fe.firebasestorage.app',
    measurementId: 'G-Y5VNF5FM9B',
  );
}
