// Enhanced Trip Data with your requested Unsplash Images
const List<Map<String, dynamic>> allTrips = [
  {
    'id': '1',
    'title': 'Bali Beach Paradise',
    'location': 'Bali, Indonesia',
    'rating': 4.9,
    'reviews': 328,
    'price': 1299,
    'date': 'Mar 15 - Mar 22',
    'image': 'https://images.unsplash.com/photo-1577717903315-1691ae25ab3f?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'airline': 'Garuda Indonesia',
    'aircraft': 'Boeing 787 Dreamliner',
    'class': 'Business Class',
    'description': 'Experience the ultimate tropical getaway with pristine beaches and vibrant culture.',
  },
  {
    'id': '2',
    'title': 'European Escapade',
    'location': 'Paris & Rome',
    'rating': 4.8,
    'reviews': 436,
    'price': 1899,
    'date': 'Apr 10 - Apr 20',
    'image': 'https://images.unsplash.com/photo-1473951574080-01fe45ec8643?q=80&w=2104&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'airline': 'Air France',
    'aircraft': 'Airbus A350-900',
    'class': 'Economy Plus',
    'description': 'A journey through the heart of Europe\'s most romantic and historic cities.',
  },
  {
    'id': '3',
    'title': 'Mountain Adventure',
    'location': 'Swiss Alps',
    'rating': 4.7,
    'reviews': 234,
    'price': 1599,
    'date': 'May 5 - May 12',
    'image': 'https://images.unsplash.com/photo-1586752488885-6ce47fdfd874?q=80&w=2113&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'airline': 'Swiss Air',
    'aircraft': 'Airbus A330',
    'class': 'Normal Chair',
    'description': 'Breathtaking views and world-class skiing in the heart of the Alps.',
  },
  {
    'id': '4',
    'title': 'Tokyo Modern',
    'location': 'Tokyo, Japan',
    'rating': 4.9,
    'reviews': 512,
    'price': 1799,
    'date': 'Jun 1 - Jun 10',
    'image': 'https://images.unsplash.com/photo-1617869884925-f8f0a51b2374?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    'airline': 'Japan Airlines',
    'aircraft': 'Boeing 777',
    'class': 'First Class',
    'description': 'Explore the neon lights and ancient temples of Japan\'s bustling capital.',
  },
  {
    'id': '5',
    'title': 'Pyramids of Giza',
    'location': 'Giza, Egypt',
    'rating': 4.9,
    'reviews': 782,
    'price': 1499,
    'date': 'Jul 8 - Jul 18',
    'image': 'https://images.unsplash.com/photo-1568322445389-f64ac2515020?q=80&w=2070&auto=format&fit=crop',
    'airline': 'EgyptAir',
    'aircraft': 'Boeing 787',
    'class': 'Business Class',
    'description': 'Witness the last standing wonder of the ancient world and explore ancient Egyptian civilization.',
  },
  {
    'id': '6',
    'title': 'Santorini Sunsets',
    'location': 'Santorini, Greece',
    'rating': 4.8,
    'reviews': 654,
    'price': 1699,
    'date': 'Aug 12 - Aug 20',
    'image': 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?q=80&w=2070&auto=format&fit=crop',
    'airline': 'Aegean Airlines',
    'aircraft': 'Airbus A320',
    'class': 'Economy Plus',
    'description': 'Experience stunning sunsets, white-washed buildings, and crystal-clear waters of the Aegean Sea.',
  },
  {
    'id': '7',
    'title': 'Iceland Northern Lights',
    'location': 'Reykjavik, Iceland',
    'rating': 4.7,
    'reviews': 421,
    'price': 1899,
    'date': 'Sep 5 - Sep 14',
    'image': 'https://images.unsplash.com/photo-1483347756197-71ef80e95f73?q=80&w=2070&auto=format&fit=crop',
    'airline': 'Icelandair',
    'aircraft': 'Boeing 737 MAX',
    'class': 'Economy',
    'description': 'Chase the magical Northern Lights and explore glaciers, geysers, and volcanic landscapes.',
  },
  {
    'id': '8',
    'title': 'Dubai Luxury',
    'location': 'Dubai, UAE',
    'rating': 4.9,
    'reviews': 891,
    'price': 2199,
    'date': 'Oct 15 - Oct 23',
    'image': 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?q=80&w=2070&auto=format&fit=crop',
    'airline': 'Emirates',
    'aircraft': 'Airbus A380',
    'class': 'First Class',
    'description': 'Indulge in ultra-modern luxury, shopping, and world-class dining in the heart of the UAE.',
  },
  {
    'id': '9',
    'title': 'Maldives Paradise',
    'location': 'Maldives',
    'rating': 5.0,
    'reviews': 567,
    'price': 2499,
    'date': 'Nov 1 - Nov 11',
    'image': 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?q=80&w=2065&auto=format&fit=crop',
    'airline': 'Singapore Airlines',
    'aircraft': 'Airbus A350',
    'class': 'Business Class',
    'description': 'Relax in overwater bungalows surrounded by turquoise waters and vibrant coral reefs.',
  },
  {
    'id': '10',
    'title': 'New York City',
    'location': 'New York, USA',
    'rating': 4.8,
    'reviews': 1024,
    'price': 1399,
    'date': 'Dec 3 - Dec 10',
    'image': 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?q=80&w=2070&auto=format&fit=crop',
    'airline': 'Delta Airlines',
    'aircraft': 'Boeing 767',
    'class': 'Premium Economy',
    'description': 'Experience the city that never sleeps with iconic landmarks, Broadway shows, and world-class museums.',
  },
  {
    'id': '11',
    'title': 'Amazon Rainforest',
    'location': 'Manaus, Brazil',
    'rating': 4.6,
    'reviews': 298,
    'price': 1599,
    'date': 'Jan 20 - Jan 30',
    'image': 'https://images.unsplash.com/photo-1516426122078-c23e76319801?q=80&w=2068&auto=format&fit=crop',
    'airline': 'LATAM Airlines',
    'aircraft': 'Boeing 787',
    'class': 'Economy',
    'description': 'Discover the world\'s largest rainforest with exotic wildlife, indigenous cultures, and river adventures.',
  },
];
